import { Rubik } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.css"; // Import CSS styles

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "FindPack",
  description: "Generated by create next app",
  icons:{
    icon: ['/favicon.ico?v=4'],
  }
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en" data-theme="emerald">
        <body className={rubik.className}>
          <div className="space-y-10 md:space-y-6">
            <Header />
            <main>
              {children}
            </main>
            <Footer />
          </div>
        </body>
      </html>
    </>
  );
}
